{
	"version": 1740398958,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/skate-sheet0.png",
		"images/body-sheet0.png",
		"images/bg-sheet0.png",
		"images/coin-sheet0.png",
		"images/dot-sheet0.png",
		"images/face-sheet0.png",
		"images/face-sheet1.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/hum.m4a",
		"media/hum.ogg",
		"media/electrical-hum-g-slightly-sharp-17887 (mp3cut.net) (1).m4a",
		"media/electrical-hum-g-slightly-sharp-17887 (mp3cut.net) (1).ogg",
		"media/altcoin hit sound.m4a",
		"media/altcoin hit sound.ogg",
		"media/game over (3).m4a",
		"media/game over (3).ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"media/bg (2).m4a",
		"media/bg (2).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}